
package corsa;

/**
 * Pista è la finestra che contiene il percorso di gara
 * @author Andrea Vallorani
 */
public class Pista extends javax.swing.JFrame {
    
    /**
     * Creates new form pista
     */
    public Pista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        corsia1 = new javax.swing.JPanel();
        icoAtleta1 = new javax.swing.JLabel();
        corsia2 = new javax.swing.JPanel();
        icoAtleta3 = new javax.swing.JLabel();
        bottoneAvvio = new javax.swing.JButton();
        statoGara = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Riavvia = new javax.swing.JButton();
        corsia3 = new javax.swing.JPanel();
        icoAtleta2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        corsia1.setBackground(new java.awt.Color(153, 51, 0));
        corsia1.setLayout(null);

        icoAtleta1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/levriero1_1.png"))); // NOI18N
        corsia1.add(icoAtleta1);
        icoAtleta1.setBounds(660, 20, 80, 40);

        corsia2.setBackground(new java.awt.Color(153, 51, 0));
        corsia2.setLayout(null);

        icoAtleta3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/lev-iloveimg-resized-iloveimg-resized.png"))); // NOI18N
        corsia2.add(icoAtleta3);
        icoAtleta3.setBounds(660, 20, 80, 50);

        bottoneAvvio.setText("VIA!");
        bottoneAvvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bottoneAvvioActionPerformed(evt);
            }
        });

        statoGara.setFont(new java.awt.Font("Rod", 0, 18)); // NOI18N
        statoGara.setText("Gara non ancora iniziata");

        jLabel1.setFont(new java.awt.Font("Rod", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/dog-iloveimg-resized.png"))); // NOI18N

        Riavvia.setText("Riavvia");
        Riavvia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RiavviaActionPerformed(evt);
            }
        });

        corsia3.setBackground(new java.awt.Color(153, 51, 0));
        corsia3.setLayout(null);

        icoAtleta2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/corsa/levriero2.png"))); // NOI18N
        corsia3.add(icoAtleta2);
        icoAtleta2.setBounds(660, 20, 70, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(corsia2, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(corsia1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(26, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(302, 302, 302))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(Riavvia)
                        .addGap(45, 45, 45)
                        .addComponent(bottoneAvvio))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(statoGara, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(corsia3, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(corsia1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(corsia3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(corsia2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statoGara)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Riavvia)
                    .addComponent(bottoneAvvio))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bottoneAvvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bottoneAvvioActionPerformed
        Giudice giudice = new Giudice(this);
        giudice.start();
        this.bottoneAvvio.setEnabled(false);
        this.Riavvia.setEnabled(false);

    }//GEN-LAST:event_bottoneAvvioActionPerformed

    private void RiavviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RiavviaActionPerformed
        icoAtleta1.setBounds(660, 15, 70, 50);
        icoAtleta2.setBounds(660, 15, 70, 50);
        icoAtleta3.setBounds(660, 15, 70, 50);
    this.Riavvia.setEnabled(false);
    this.bottoneAvvio.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_RiavviaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Riavvia;
    private javax.swing.JButton bottoneAvvio;
    private javax.swing.JPanel corsia1;
    private javax.swing.JPanel corsia2;
    private javax.swing.JPanel corsia3;
    public javax.swing.JLabel icoAtleta1;
    public javax.swing.JLabel icoAtleta2;
    public javax.swing.JLabel icoAtleta3;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel statoGara;
    // End of variables declaration//GEN-END:variables
}
